julia:
  - "1.0"
  - "1.2"
  - "1.3"
  - nightly

language: julia

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

notifications:
  email: false

os:
  - linux

script: 
  - set -e
  - julia --code-coverage --inline=no -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
