branches:
  only:
  - master
  - staging
  - trying
  - /^release\/.*$/ # release branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

julia:
  - "1.0"
  - "1.1"
  - "1.2"
  - "1.3"

language: julia

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

os:
  - linux

script: julia --code-coverage --inline=no -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

after_success: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  include:
    - stage: VersionVigilante
      julia: "1.3"
      script:
        - set -e
        - julia -e 'using Pkg; Pkg.add(Pkg.PackageSpec(url = "https://github.com/bcbi/VersionVigilante.jl"))'
        - julia -e 'using VersionVigilante; VersionVigilante.main("https://github.com/bcbi/VersionVigilante.jl")'
      after_success: true
