branches:
  only:
  - master
  - staging
  - trying
  - /^release\/.*$/ # release branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

julia:
  - "1.0"
  - "1.2"
  - "1.3"
  - nightly

language: julia

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

notifications:
  email: false

os:
  - linux

script: julia --code-coverage --inline=no -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

after_success: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  include:
    - stage: VersionVigilante
      julia: "1.2"
      script:
        - set -ev
        - julia --code-coverage --inline=no -e 'using Pkg; Pkg.add(Pkg.PackageSpec(url = "https://github.com/bcbi/VersionVigilante.jl"))'
        - julia --code-coverage --inline=no -e 'using VersionVigilante; VersionVigilante.main("https://github.com/bcbi/VersionVigilante.jl")'
      after_success: true
