name = "VersionVigilante"
uuid = "227ca074-f042-4221-a2ff-40f0acdddd34"
authors = ["Dilum Aluthge", "Brown Center for Biomedical Informatics"]
version = "0.1.3"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Test"]
