name: VersionVigilante

on:
  push:
    branches:
      - staging
      - trying

jobs:
  VersionVigilante:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
      - name: VersionVigilante.main
        id: versionvigilante_main
        # BEGIN: Uncomment these lines if this is a private repository
        # run: |
        #   julia -e 'using Pkg; Pkg.add("VersionVigilante")'
        #   julia -e 'using VersionVigilante; VersionVigilante.main("https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}")'
        # END: Uncomment these lines if this is a private repository
        # BEGIN: Comment out these lines if this is NOT a private repository
        run: |
          julia -e 'using Pkg; Pkg.add("VersionVigilante")'
          julia -e 'using VersionVigilante; VersionVigilante.main("https://github.com/${{ github.repository }}")'
        # END: Comment out these lines if this is NOT a private repository
